FROM node:16.13.0-alpine as base

WORKDIR /usr/api/
COPY package.json yarn.lock tsconfig.json ./
RUN yarn

COPY ./src ./src

FROM base as development

ENV NODE_ENV=development

FROM base as build

ENV NODE_ENV=production
RUN yarn build

FROM build as production

ENV NODE_PATH=./build

COPY --from=build /usr/api/build /usr/api/build
COPY .env.production ./

RUN yarn install --production
RUN yarn global add pm2